delete from PREIS 
where 
P_LEISTUNGSTYP=3 
and P_LEISTSEQ in 
(
select ZI_SEQ from ZIMMER,HOTEL where ZI_HOSEQ=HO_SEQ and 
  (
    
HO_DESTINATION,HO_HOTELCODE)=('LAS','BELLAG')
or (HO_DESTINATION,HO_HOTELCODE)=('MRU','LUXGAU')
or (HO_DESTINATION,HO_HOTELCODE)=('LAS','PARIS')
or (HO_DESTINATION,HO_HOTELCODE)=('MCT','INTCON')
or (HO_DESTINATION,HO_HOTELCODE)=('PRI','LEREPA')
or (HO_DESTINATION,HO_HOTELCODE)=('KBV','LAYANA')
or (HO_DESTINATION,HO_HOTELCODE)=('HKT','BANTRE')
or (HO_DESTINATION,HO_HOTELCODE)=('LAS','PARIS')
or (HO_DESTINATION,HO_HOTELCODE)=('MCT','INTCON')
or (HO_DESTINATION,HO_HOTELCODE)=('PRI','LEREPA')
or (HO_DESTINATION,HO_HOTELCODE)=('KBV','LAYANA')
or (HO_DESTINATION,HO_HOTELCODE)=('MLE','SIXLAA')

  )
)